server:
  port: 8080

spring:
  application:
    name: api-gateway
  #  match voi path firstfit
  #  chi lam nhiem vu check token va dieu huong toi dung port
  cloud:
    gateway:
      routes:
        # can cu vao header de biet api rest nay la 1 api yeu cau ugrade len socket
        #        sau khi ket noi thanh cong thi cac request sau khi qua k qua gateway nua
        #        ban chat ban dau ws gui 1 http rq de yeu cau ket noi, tai day se tan dung duoc http security
        # 81.82 cua weavate
        - id: identity-service
          uri: http://localhost:8084
          predicates:
            - Path=/identity/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5      # Tái nạp 5 request/giây
                redis-rate-limiter.burstCapacity: 10     # Cho phép tối đa 10 request burst
                key-resolver: "#{@ipKeyResolver}"

        - id: shop-service
          uri: http://localhost:8083
          predicates:
            - Path=/shop/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5      # Tái nạp 5 request/giây
                redis-rate-limiter.burstCapacity: 10     # Cho phép tối đa 10 request burst
                key-resolver: "#{@ipKeyResolver}"

        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/notifications/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5      # Tái nạp 5 request/giây
                redis-rate-limiter.burstCapacity: 10     # Cho phép tối đa 10 request burst
                key-resolver: "#{@ipKeyResolver}"

        - id: message-service
          uri: http://localhost:8085
          predicates:
            - Path=/messages/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5      # Tái nạp 5 request/giây
                redis-rate-limiter.burstCapacity: 10     # Cho phép tối đa 10 request burst
                key-resolver: "#{@ipKeyResolver}"

        - id: order-service
          uri: http://localhost:8086
          predicates:
            - Path=/orders/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5      # Tái nạp 5 request/giây
                redis-rate-limiter.burstCapacity: 10     # Cho phép tối đa 10 request burst
                key-resolver: "#{@ipKeyResolver}"

        - id: main-service
          uri: http://localhost:8081
          predicates:
            - Path=/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5      # Tái nạp 5 request/giây
                redis-rate-limiter.burstCapacity: 10     # Cho phép tối đa 10 request burst
                key-resolver: "#{@ipKeyResolver}"
  data:
    redis:
      host: localhost
      port: 6379



jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG



