server:
  port: 8082

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: main-service
          uri: http://localhost:8080
          predicates:
            - Path=/**
#match  path cu the hon neu path gan giong nhau
        - id: notification-service
          uri: http://localhost:8081
          predicates:
            - Path=/notification/**
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds