server:
  port: 8082

spring:
  application:
    name: api-gateway
#  match voi path firstfit
#  chi lam nhiem vu check token va dieu huong toi dung port
  cloud:
    gateway:
      routes:
#        doi thanh ws chu kp http de service biet day la api socket
#        sau khi ket noi thanh cong thi cac request sau khi qua k qua gateway nua
        - id: notification-ws
          uri: ws://localhost:8081
          predicates:
            - Path=/ws-notification/**

        - id: main-ws
          uri: ws://localhost:8080
          predicates:
            - Path=/ws/**

        - id: notification-service
          uri: http://localhost:8081
          predicates:
            - Path=/notifications/**

        - id: main-service
          uri: http://localhost:8080
          predicates:
            - Path=/**


jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds