server:
  port: 8082

spring:
  application:
    name: api-gateway
#match voi path firstfit
  cloud:
    gateway:
      routes:
        - id: notification-service
          uri: http://localhost:8081
          predicates:
            - Path=/notifications/**
        - id: main-service
          uri: http://localhost:8080
          predicates:
            - Path=/**

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds