server:
  port: 8080

spring:
  application:
    name: api-gateway
  #  match voi path firstfit
  #  chi lam nhiem vu check token va dieu huong toi dung port
  cloud:
    gateway:
      routes:
        #        doi thanh ws chu kp http de service biet day la api socket
        #        sau khi ket noi thanh cong thi cac request sau khi qua k qua gateway n-ua
        #        ban chat ban dau ws gui 1 http rq de yeu cau ket noi, tai day se tan dung duoc http security

        - id: shop-service
          uri: http://localhost:8083
          predicates:
            - Path=/shop/**

        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/notifications/**

        - id: main-service
          uri: http://localhost:8081
          predicates:
            - Path=/**

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

